--[[
    Model configuration for the Arrows module
    
    This module defines all the data structures, configurations, and constants used
    throughout the Arrows system. It includes:
    
    - Type definitions (KeyType, Direction)
    - Visual styling (colors, dimensions, animations)
    - Key mappings and keyboard configurations
    - Sound settings
    - Timing configurations
    - State definitions
]]

local M = {}

-- Type Definitions
---@class KeyType
---@field VIM string Vim-style navigation key
---@field ARROW string Arrow key navigation
---@field BACK string Back command key
M.KeyType = {
    VIM = "vim",
    ARROW = "arrow",
    BACK = "back"
}

---@class Direction
---@field UP string Up direction
---@field DOWN string Down direction
---@field LEFT string Left direction
---@field RIGHT string Right direction
---@field BACK string Back command
M.Direction = {
    UP = "up",
    DOWN = "down",
    LEFT = "left",
    RIGHT = "right",
    BACK = "back"
}

-- Symbols and Labels
M.SYMBOLS = {
    [M.Direction.UP] = "⬆",
    [M.Direction.DOWN] = "⬇",
    [M.Direction.LEFT] = "⬅",
    [M.Direction.RIGHT] = "➡",
    [M.Direction.BACK] = "▲"
}

M.LABELS = {
    [M.Direction.UP] = "K",
    [M.Direction.DOWN] = "J",
    [M.Direction.LEFT] = "H",
    [M.Direction.RIGHT] = "L",
    [M.Direction.BACK] = "Back"
}

-- Visual Style Configuration
---@class Style
M.Style = {
    -- Font configurations
    FONT = {
        FAMILY = '"Proxima Nova", "SF Pro", sans-serif',
        WEIGHT = "600",
        SIZES = {
            SYMBOL = {
                DEFAULT = "1em",
                BACK = "0.85em"
            },
            LABEL = {
                DEFAULT = "0.8em",
                BACK = "0.65em"
            }
        }
    },
    
    -- Color configurations for different states and elements
    COLORS = {
        BACKGROUND = {
            DEFAULT = "rgba(30, 30, 30, 1)",  -- Dark gray for vim
            ARROW = "rgba(180, 0, 0, 1)",     -- Red for arrow keys
        },
        SYMBOL = {
            DEFAULT = "white",                 -- Default symbol color
            ARROW = "#4B0000",                -- Dark red for arrow keys
            BACK = "white"                    -- White for back command
        },
        LABEL = {
            DEFAULT = "#666666",              -- Gray for vim
            ARROW = "white",                  -- White for arrow keys
            BACK = "#666666"                  -- Gray for back command
        }
    },
    
    -- Window dimensions and positioning
    WINDOW = {
        WIDTH = 90,                          -- Width of the display window
        HEIGHT = 120,                        -- Height of the display window
        MARGIN = 20,                         -- Margin from screen edges
        BORDER_RADIUS = 12,                  -- Border radius for the arrow block
        PADDING = 20                         -- Internal padding for the arrow block
    },
    
    -- Animation timing and configuration
    ANIMATION = {
        FADE_DURATION = 0.8,                 -- Duration of fade animation in seconds
        FADE_STEPS = 10,                     -- Number of steps in fade animation
        DISPLAY_DURATION = 2.0,              -- How long to display before fading
        TRANSITION_DELAY = 0.01              -- Delay between sound transitions
    }
}

-- Sound Configuration
---@class SoundConfig
M.Sound = {
    -- Volume levels
    VOLUME = {
        NORMAL = 0.2,                        -- Normal volume level
        MUTED = 0.0                          -- Muted volume level
    },
    
    -- Sound file paths (relative to sounds directory)
    PATHS = {
        NORMAL = "%s.wav",                   -- Pattern for normal sounds
        DISSONANT = "dissonant/%s.wav",      -- Pattern for dissonant sounds
        BACK = "up_deeper.wav"               -- Back command sound
    }
}

-- Timing Configuration
---@class TimingConfig
M.Timing = {
    CELEBRATION = {
        TIMEOUT = 2.0,                       -- Celebration window timeout
        DURATION = 1.0,                      -- Celebration animation duration
        REPEAT_COUNT = 3,                    -- Number of times to repeat celebration
        REPEAT_DELAY = 0.2                   -- Delay between celebration repeats
    },
    
    KEY = {
        DEBOUNCE = 0.1,                      -- Key press debounce time
        DOUBLE_TAP = 0.3,                    -- Double-tap detection threshold
        HYPER_RESET = 0.1                    -- Hyper key reset delay
    }
}

-- Initial state
M.State = {
    INITIAL = {
        inKeySequence = false,               -- Not in a key sequence
        isHyperGenerated = false             -- Not generated by hyper key
    }
}

-- Key mappings
---@class KeyMapping
---@field vim string The vim key for this direction
---@field keycode number The keycode for this direction
M.KeyMappings = {
    [M.Direction.UP] = { vim = "k", keycode = 126 },    -- Up arrow
    [M.Direction.DOWN] = { vim = "j", keycode = 125 },  -- Down arrow
    [M.Direction.LEFT] = { vim = "h", keycode = 123 },  -- Left arrow
    [M.Direction.RIGHT] = { vim = "l", keycode = 124 }, -- Right arrow
    [M.Direction.BACK] = { vim = "b", keycode = 116 }   -- Page Up
}

-- Special key codes
---@class SpecialKeys
M.SpecialKeys = {
    ESCAPE = 53,           -- Escape key code
    CELEBRATION = 126      -- Up arrow for celebration (same as UP direction)
}

return M 